export { default as Login } from './Login'
export { default as Cadastrar } from './Cadastrar'
export { default as Home } from './Home'
export { default as Diario } from './Diario'
export { default as Texto } from './Texto'
export { default as Camera } from './Camera'
export { default as Map } from './Map'
export { default as File } from './File'
